config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get '/about', to: "homes#about"
    resources :users, only: [:show, :edit, :update] do
      resources :likes, only: [:index]
      member do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
    resources :posts, only: [:new, :create, :show, :index, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show]
    patch 'users/:id/withdraw', to: "users#withdraw"
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user # ユーザーとの関連付け
  belongs_to :category # カテゴリとの関連付け
  has_many :likes, dependent: :destroy # いいね機能（関連付け）
  has_many :comments, dependent: :destroy #コメントとの関連付け
  #ステータスが有効である会員のコメントのみ表示できるようにメソッドを作成
  has_many :active_comments, -> {joins(:user).where(user: {is_deleted: false})}, class_name: "Comment"

  #バリデーション
  with_options presence: true do
    validates :item_name
    validates :introduction
    validates :brand
    validates :usability
    validates :ingredient1
    validates :ingredient2
    validates :ingredient3
    validates :price
    validates :image
    validates :star
  end

  enum usability: { moist: 0, refresh: 1 } # 使用感選択用
  # moist   = しっとり
  # refresh = さっぱり

  def liked_by?(user)
    likes.exists?(user_id: user.id) # likeテーブル内にuser_idがあるか確認
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).per(10)
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @post_user = @post.user
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="row justify-content-md-center pt-5">
  <div class="col-md">
    <h2 class="font-weight-bold">投稿一覧</h2>
  </div>
</div>

<div class="row pt-3">
  <div class="col-md">
    <table class="table">
      <thead>
        <tr>
          <th scope="col" style="width: 10%">投稿日</th>
          <th scope="col" style="width: 20%">投稿者</th>
          <th scope="col">商品名</th>
          <th scope="col">商品説明</th>
        </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.created_at.strftime('%Y/%m/%d') %></td>

          <td class="text-break">
            <%= link_to admin_user_path(post.user.id) do %>
            　<%= post.user.name %>
            <% end %>
          </td>

          <td class="text-break">
            <%= link_to admin_post_path(post.id) do %>
              <%= post.item_name %>
            <% end %>
          </td>

          <td class="text-break"><%= post.introduction %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row justify-content-md-center pt-3">
  <div class="col-md-4 ml-5">
    <%= paginate @posts %>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/admin/posts/show.html.erb
<div class="row pt-3">
  <div class="col-md text-right">
    投稿者：<%= @post_user.name %>/
    更新日時 <%= @post.created_at.strftime('%Y/%m/%d') %>
  </div>
</div>

<div class="row  pt-5">
  <%# 商品詳細画面左側 %>
  <div class="col-md-5">
    <%# 投稿詳細画面左側の部分テンプレート%>
    <%= render 'public/posts/show_left', post: @post %>
  </div>

  <%# 商品詳細画面右側 %>
  <div class="col-md-7">
    <%# 商品詳細画面右側の部分テンプレート %>
    <%= render 'public/posts/show_right', post: @post %>

      <div class="text-right">
        <%= link_to "投稿を削除する", admin_post_path(@post.id), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-outline-danger" %>
      </div>
  </div>
</div>

<div class="row pt-5">
  <div class="col-md-7">
    <div>コメント <%= @post.active_comments.count %> 件</div>
    <%# コメント内容 %>
    <% @post.active_comments.each do |post_comment| %>
      <div class="text-break border border-dark rounded mt-3">
        <%= image_tag post_comment.user.get_profile_image(100, 100) %>
        <%= link_to user_path(post_comment.user.id) do %>
          <%= post_comment.user.name %>
        <% end %>
        <%= post_comment.comment %>
        <p class="text-right">
          <%= post_comment.created_at.strftime('%Y/%m/%d') %>
          <%= link_to "削除", admin_comment_path(post_comment.id), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-outline-danger btn-sm" %>
        </p>
    </div>
    <% end %>
  </div>
</div>