config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get '/about', to: "homes#about"
    resources :users, only: [:show, :edit, :update] do
      resources :likes, only: [:index]
      member do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
    resources :posts, only: [:new, :create, :show, :index, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show]
    patch 'users/:id/withdraw', to: "users#withdraw"
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :posts, dependent: :destroy #投稿との関連付け
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @category   = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render 'index'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to admin_categories_path
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="row justify-content-md-center pt-5">
  <div class="col-md">
    <h2 class="font-weight-bold">カテゴリ名を変更</h2>
  </div>
</div>

<div class="row pt-5">
  <%# カテゴリ追加フォーム %>
  <div class="col-md-6">
    <%= form_with model: @category, url: admin_category_path(@category.id), method: :patch do |f| %>
      <%= f.label :name, "カテゴリ名", class:"font-weight-bold mr-3" %>
      <%= f.text_field :name %>
      <%= f.submit "変更する", class:"btn btn-outline-success ml-2" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row justify-content-md-center pt-5">
  <div class="col-md">
    <h2 class="font-weight-bold">カテゴリ一覧</h2>
  </div>
</div>

<div class="row">
  <div class="col-md">
    <% if @category.errors.any? %>
      <%= @category.errors.count %>件のエラーが発生しました
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

<div class="row pt-5">
  <%# カテゴリ追加フォーム(画面左側) %>
  <div class="col-md-6">
    <%= form_with model: @category, url: admin_categories_path do |f| %>
      <%= f.label :name, "カテゴリ名", class:"font-weight-bold mr-3" %>
      <%= f.text_field :name %>
      <%= f.submit "追加する", class:"btn btn-outline-success ml-2" %>
    <% end %>
  </div>

  <%# カテゴリ一覧(画面右側) %>
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class="text-center">カテゴリ</th>
        </tr>
      </thead>
      <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to "編集", edit_admin_category_path(category.id), class:"btn btn-outline-success btn-sm" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>