config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get '/about', to: "homes#about"
    resources :users, only: [:show, :edit, :update] do
      resources :likes, only: [:index]
      member do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
    resources :posts, only: [:new, :create, :show, :index, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show]
    patch 'users/:id/withdraw', to: "users#withdraw"
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #バリデーション
  with_options presence: true do
    validates :name
    validates :gender
    validates :skin_type
  end

  has_one_attached :profile_image #プロフィール画像用

  has_many :posts, dependent: :destroy #投稿との関連付け
  has_many :likes, dependent: :destroy #いいね機能（関連付け）
  has_many :like_posts, through: :likes, source: :post #中間テーブル(likes)を通したPostモデルとの関連付け
  has_many :comments, dependent: :destroy #コメントとの関連付け

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.gender = "woman"
      user.skin_type = "normal"
    end
  end

  enum gender: { man: 0, woman: 1 } # 性別選択用

  enum skin_type: { normal: 0, oily: 1, dry: 2, mix: 3, unknown: 4 } # 肌タイプ選択用
  # normal  = 普通肌
  # oily    = 脂性肌
  # dry     = 乾燥肌
  # mix     = 混合肌
  # unknown = わからない
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_users_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="row justify-content-md-center pt-5">
  <div class="col-md">
    <h2 class="font-weight-bold">会員一覧</h2>
  </div>
</div>

<div class="row pt-3">
  <div class="col-md">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">名前</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= link_to admin_user_path(user.id) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td>
            <% if user.is_deleted? %>
              <p>退会</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row justify-content-md-center pt-3">
  <div class="col-md-4 ml-5">
    <%= paginate @users %>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/admin/users/show.html.erb
<div class="row pt-5">
  <div class="col-md">
    <h2 class="font-weight-bold"><%= @user.name %>さんのプロフィール</h2>
  </div>
</div>


<div class="row justify-content-md-center pt-5">
  <%# ユーザー詳細 %>
  <div class="col-md-4 pt-3">
    <%# ユーザーのプロフィール情報の部分テンプレート %>
    <%= render 'public/users/show', user: @user %>

    <% if @user.is_deleted? %>
      <p class="text-danger text-center mr-3 pt-2">退会済みです</p>
    <% else %>
      <p class="text-center mr-3 pt-2">
        <%= link_to "利用停止する", admin_path, method: :patch, data: {confirm: "利用停止しますか？"}, class:"btn btn-outline-danger" %>
      </p>
    <% end %>
  </div>
</div>