config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get '/about', to: "homes#about"
    resources :users, only: [:show, :edit, :update] do
      resources :likes, only: [:index]
      member do
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
    resources :posts, only: [:new, :create, :show, :index, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      collection do
        get "search"
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show]
    patch 'users/:id/withdraw', to: "users#withdraw"
    resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :posts, dependent: :destroy #投稿との関連付け
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user #ユーザーとの関連付け
  belongs_to :post #投稿との関連付け
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user # ユーザーとの関連付け
  belongs_to :category # カテゴリとの関連付け
  has_many :likes, dependent: :destroy # いいね機能（関連付け）
  has_many :comments, dependent: :destroy #コメントとの関連付け
  #ステータスが有効である会員のコメントのみ表示できるようにメソッドを作成
  has_many :active_comments, -> {joins(:user).where(user: {is_deleted: false})}, class_name: "Comment"

  #バリデーション
  with_options presence: true do
    validates :item_name
    validates :introduction
    validates :brand
    validates :usability
    validates :ingredient1
    validates :ingredient2
    validates :ingredient3
    validates :price
    validates :image
    validates :star
  end

  enum usability: { moist: 0, refresh: 1 } # 使用感選択用
  # moist   = しっとり
  # refresh = さっぱり

  def liked_by?(user)
    likes.exists?(user_id: user.id) # likeテーブル内にuser_idがあるか確認
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #バリデーション
  with_options presence: true do
    validates :name
    validates :gender
    validates :skin_type
  end

  has_one_attached :profile_image #プロフィール画像用

  has_many :posts, dependent: :destroy #投稿との関連付け
  has_many :likes, dependent: :destroy #いいね機能（関連付け）
  has_many :like_posts, through: :likes, source: :post #中間テーブル(likes)を通したPostモデルとの関連付け
  has_many :comments, dependent: :destroy #コメントとの関連付け

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.gender = "woman"
      user.skin_type = "normal"
    end
  end

  enum gender: { man: 0, woman: 1 } # 性別選択用

  enum skin_type: { normal: 0, oily: 1, dry: 2, mix: 3, unknown: 4 } # 肌タイプ選択用
  # normal  = 普通肌
  # oily    = 脂性肌
  # dry     = 乾燥肌
  # mix     = 混合肌
  # unknown = わからない
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def index
    @comments = Comment.page(params[:page]).per(10)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).per(10)
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @post_user = @post.user
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_users_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeautySkin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Beauty Skin</a>
          <ul class="nav justify-content-end">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "About", about_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "投稿一覧", admin_posts_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "カテゴリ一覧", admin_categories_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "コメント一覧", admin_comments_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></button>
            </li>
          <% elsif user_signed_in? %>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "About", about_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "新規投稿", new_post_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "投稿一覧", posts_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "マイページ", user_path(current_user.id), class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %></button>
            </li>
          <% else %>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "About", about_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %></button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary mr-3"><%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %></button>
            </li>
          <% end %>

          </ul>
        </div>
      </nav>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>

    </footer>
  </body>
</html>